Repository Zakey-Pilot/html-css-project, pull requests merged in 2025-02, with the labels that each got.

#4 create and write group norms
  planning/group-norms.md
Labels: review

#11 create and write project definition
  planning/project-definition.md
Labels: review

#13 updating communication.md and cspell.json files
  .cspell.json
  planning/communication.md
Labels: planning, review

#22 update user persona
  planning/user-personas.md
Labels: review

#23 Update design file
  planning/design.md
  public/assets/project-wireframe.png
Labels: review

#24 add backlog
  package-lock.json
  package.json
  planning/backlog.md
Labels: planning, review

#25 added main info section
  index.html
  styles/index.css
Labels: review

#26 15 feature page title
  index.html
  public/assets/happy-tree.jpg
  styles/index.css
Labels: feature

#30 edit image size
  index.html
Labels: bug

#31 Extra info
  index.html
  styles/index.css
Labels: feature

#32 add introduction
  index.html
  styles/index.css
Labels: feature

#33 adding the navbar section
  index.html
  styles/index.css
Labels: feature

#35 Add footer
  index.html
  styles/index.css
Labels: feature

#34 adding the bounce animation
  styles/index.css
Labels: feature

#37 update head title and meta data
  index.html
Labels: enhancement, review

#40 add learning goal
  .cspell.json
  planning/learning-goals.md
Labels: planning

#41 update readme file
  README.md
  public/assets/screenshot.png
Labels: documentation, review

#43 specify deadline
  planning/constraints.md
Labels: planning
